apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o payment-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o payment-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
        - image: fontyssa/payment-service
          name: payment-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
