apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o payment-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: paymentservice
  name: paymentservice
spec:
  containers:
    - image: fontyssa/payment-service
      name: paymentservice
      ports:
        - containerPort: 80
      resources: {}
  restartPolicy: OnFailure
