apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o router-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: router-service
  name: router-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: router-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o router-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: router-service
    spec:
      containers:
        - env:
            - name: REGION_TYPE
              value: {{.Values.region.type}}
            - name: REGION
              value: {{.Values.region.area}}
            - name: CAR_SERVICE_URL
              value: {{.Values.serviceUri.car}}
            - name: PAYMENT_SERVICE_URL
              value: {{.Values.serviceUri.payment}}
            - name: MASSTRANSIT_INPUT
              value: {{.Values.masstransit.input}}
            - name: MASSTRANSIT_OUTPUT
              value: {{.Values.masstransit.output}}
            - name: RABBITMQ_HOST
              value: {{.Values.rabbitmq.host}}
            - name: RABBITMQ_PORT
              value: {{.Values.rabbitmq.port}}
            - name: RABBITMQ_USERNAME
              value: {{.Values.rabbitmq.user}}
            - name: RABBITMQ_PASSWORD
              value: {{.Values.rabbitmq.password}}
            - name: RABBITMQ_QUEUE
              value: {{.Values.rabbitmq.queue}}
            - name: RABBITMQ_VIRTUAL_HOST
              value: {{.Values.rabbitmq.virtualHost}}
            - name: CACHE_FOLDER
              value: /osmnx-cache
            - name: LOG_LEVEL
              value: ERROR
          image: fontyssa/router-service
          name: router-service
          resources: { }
          volumeMounts:
            - mountPath: /osmnx-cache
              name: osmnx-cache
      restartPolicy: Always
      volumes:
        - name: osmnx-cache
          persistentVolumeClaim:
            claimName: osmnx-cache
