apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: data-service
  name: data-service
spec:
  ports:
    - name: "5054"
      port: 5054
      targetPort: 80
  selector:
    io.kompose.service: data-service
