apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongodb-coordinateservice
  name: mongodb-coordinateservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-coordinateservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: mongodb-coordinateservice
    spec:
      containers:
        - image: mongo
          name: mongodb-coordinateservice
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
